/**
 * PlayFab API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const ItemType = {
  Unknown: 'Unknown',
  Commodities: 'Commodities',
  Weapons: 'Weapons',
  Armors: 'Armors',
  Accessories: 'Accessories',
  Tools: 'Tools',
} as const;
export type ItemType = (typeof ItemType)[keyof typeof ItemType];
