/**
 * PlayFab API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const JobType = {
  Unknown: 'Unknown',
  HerbCollector: 'HerbCollector',
  Lumberjack: 'Lumberjack',
  BlackSmith: 'BlackSmith',
  Miner: 'Miner',
} as const;
export type JobType = (typeof JobType)[keyof typeof JobType];
