/**
 * PlayFab API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillPerk } from './skillPerk';
import { PlayerSkillExperience } from './playerSkillExperience';

export interface PlayerSkill {
  playerSkillId: string;
  skillName: string;
  skillLevel: number;
  currentSkillExp: number;
  playerSkillExperience: PlayerSkillExperience;
  skillPerks: SkillPerk[];
}
