/**
 * PlayFab API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemData } from './itemData';

export interface PlayerStorageItem {
  storageItemId: string;
  itemCount: number;
  itemData: ItemData;
}
