/**
 * Garden Game API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageItem } from './storageItem';


export interface PlayerStorage { 
    playerStorageId?: string;
    items?: Array<StorageItem>;
}

