/**
 * PlayFab API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestData } from './questData';

export interface PlayerQuest {
  playerQuestId: string;
  isCompleted: boolean;
  completedQuestDetails: string[];
  questData: QuestData;
}
