/**
 * Garden Game API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestDataQuestRewardsInner } from './questDataQuestRewardsInner';
import { QuestDataQuestDetailsInner } from './questDataQuestDetailsInner';


export interface QuestData { 
    questId?: string;
    questName?: string;
    isMainQuest?: boolean;
    questDescription?: string;
    questDetails?: Array<QuestDataQuestDetailsInner>;
    questRewards?: Array<QuestDataQuestRewardsInner>;
}

