/**
 * Garden Game API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SkillExperience { 
    playerSkillExperienceId: string;
    currentExp: number;
    currentLevel: number;
    nextLevelExp: number;
    maxLevel: number;
}

