/**
 * Garden Game API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SkillPerk { 
    skillPerkId: string;
    skillPerkName: string;
    skillPerkDescription: string;
    skillPerkIcon: string;
}

